### PR TITLE
update welcome email to use help text URLs

### PR DESCRIPTION
**Pull request by estenberg**
Signed-off-by: Eystein Måløy Stenberg <eystein.maloy.stenberg@cfengine.com>

### CODE REVIEW

**Comment by estenberg** [comment]
Ticket: https://tracker.mender.io/browse/MC-195

**Comment by estenberg** [comment]
The build failed, but looks like for unrelated reasons? @GregorioDiStefano perhaps you could give some insight?

**Comment by GregorioDiStefano** [comment]
sign off is missing

**Comment by estenberg** [comment]
Added changelog.

**Review by maciejmrowiec — APPROVED** [review]

**Pull request merged**
