### PR TITLE
MC-884 send_email: upgrading python client to the latest version (2.12.4)

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Review by 0lmi — APPROVED** [review]
Looks good

**Comment by merlin-northern** [comment]
@lluiscampos can I ignore integration tests here?

**Comment by lluiscampos** [comment]
It is strange that so many tests failed, but at first glance they are seem the known spurious error.

But as you asked, I have started a new run just in case. Follow the progress in [Jenkins 3597](https://mender-jenkins.mender.io/job/mender-builder/3597/).

**Comment by merlin-northern** [comment]
> It is strange that so many tests failed, but at first glance they are seem the known spurious error.
> 
> But as you asked, I have started a new run just in case. Follow the progress in [Jenkins 3597](https://mender-jenkins.mender.io/job/mender-builder/3597/).

thanks! now it passed! but I have to rebase, so lets hope it iwll pass this time as well.

**Comment by merlin-northern** [comment]
> > It is strange that so many tests failed, but at first glance they are seem the known spurious error.
> > But as you asked, I have started a new run just in case. Follow the progress in [Jenkins 3597](https://mender-jenkins.mender.io/job/mender-builder/3597/).
> 
> thanks! now it passed! but I have to rebase, so lets hope it iwll pass this time as well.

@lluiscampos you did some magic :) now it failed again after I pressed "update branch" can I start a new run and do the same as you did?

**Comment by lluiscampos** [comment]
The errored test is okey :+1:

**Comment by merlin-northern** [comment]
> The errored test is okey

thanks @lluiscampos ! I am rebasing and lets see.

**Pull request merged**
